### ISSUE TITLE
Error: Checksum mismatch cbdadf93f550a847 != 8b992499f9ee7aac

### ISSUE THREAD

**Issue by ghost** [mhsjlw/pocket-minecraft-protocol#350]
My code: https://pastebin.com/AvQFuwNp

Error: Checksum mismatch cbdadf93f550a847 != 8b992499f9ee7aac

**Comment by extremeheat** [comment]
Can you provide a minimum set of code to reproduce, without chunks? The server example is a bit outdated here, and we are open to PRs for an update to it. Could be a duplicate of https://github.com/PrismarineJS/bedrock-protocol/issues/163

**Comment by ghost** [comment]
> Could be a duplicate of #163

This isnt duplicate of #163. The client in this case can load the map but only on old minecraft versions (1.17.10)

> Can you provide a minimum set of code to reproduce, without chunks?

This code isn't possible to reproduce without sending chunks to the client on 1.19.62

**Comment by extremeheat** [comment]
If it does not happen if you don't send chunks, it certainly sounds like #158 and #163 to me. If you can reproduce this issue without sending chunk contents or empty chunks then we can keep this open, otherwise there's no need for 3 issues tracking the same thing. 

The checksum mismatch issue here is likely a cascading failure from an issue with the login procedure (not sending correct packet or chunks are invalid/rejected). If the Server works through the Relay there should not be any problems using a standalone server -- if you'd like to investigate this issue you can compare the sequence in a vanilla client with Relay to see if any packets are missing. It could be our example needs to be fixed.

**Comment by ghost** [comment]
I managed to fix that issue, and the client was able to render the chunks.

**Comment by ghost** [comment]
The issue was because of network_chunk_publisher_update
