### ISSUE TITLE
bedrock bots not working

### ISSUE THREAD

**Issue by zernix2077** [mhsjlw/pocket-minecraft-protocol#360]
Maybe I'm just stupid and don't understand something, but bedrock bots don't work! mineflayer 4.8.1, latest bedrock protocol, tried python 3.7 and 3.10, javascript, server cores - pocket mine and nukkit, minecraft versions - 1.19.50, 60 and 70
![image](https://user-images.githubusercontent.com/110056737/228483293-a4a00809-0720-43fc-9aa0-8e7abe4c74ad.png)
all the bot is capable of is to join to the server, nothing else. It does not react to absolutely any external factors, does not see a single message, not a single block, and cannot answer - do not turn around, or write messages. Even on the server, it has no gravity/repulsion from hits. the only thing that works in the bot code is parameters that are not related to the game, for example, endlessly writing "123" to the console logs. My code (I've tried many other features before) -
```python

import sys, re, time
from javascript import require, On, Once, console
bedrock = require('bedrock-protocol')
pathfinder = require('mineflayer-pathfinder')

RANGE_GOAL = 1
BOT_USERNAME = 'losphed1'

bot = bedrock.createClient({
  'host': '188.165.55.40',
  'port': 19132,
  'username': BOT_USERNAME,
  'offline': True
})

def say_position(username):
    p = bot.entity.position
    bot.chat(f"I am at {p.toString()}")
    if username in bot.players:
        p = bot.players[username].entity.position
        bot.chat(f"You are at {p.toString()}")

@On(bot, "chat")
def handle(this, username, message, *args):
    console.log(f'{username}: {message}')

while True:
    def test(this):
        time.sleep(5.5)
        bot.chat("test")


```
I really hope this can be fixed!

**Comment by extremeheat** [comment]
You are not understanding the libraries correctly. This package is for working with the Minecraft bedrock edition protocol, which means that in order to use it, you must listen to packets and send packets to the server yourself to get the functionality you want. 

Mineflayer is a higher level lib that takes care of the network packets and provides a stable API for creating Minecraft bots. Mineflayer does not support bedrock edition at the moment. There is no "bot.players" or anything like that in bedrock-protocol. Your code used here is not valid bedrock-protocol usage.

**Comment by zernix2077** [comment]
really? apparently I misunderstood everything, but even now it's not very clear to me either. how would I be able to listen and send packets? do I need any third-party proxy for this?

**Comment by zernix2077** [comment]
I think I figured it out. I need to use another server between the bot and the right server, which is on this github, right?

**Comment by extremeheat** [comment]
No, see the documentation on this repo including the README and examples for usage.
