### ISSUE TITLE
Automatically fetch Mojang public key

### ISSUE THREAD

**Issue by outsparkled** [mhsjlw/pocket-minecraft-protocol#447]
As you may know, the Mojang public key, currently stored in [src/handshake/constants.js](https://github.com/PrismarineJS/bedrock-protocol/blob/master/src/handshake/constants.js), was updated recently. 

When my bedrock-protocol application failed to connect to servers with only a cryptic message, it took me a long time to realize why a dependency update fixed the issue.

While I am aware that such an update is by no means a frequent occurrence, I do think it could be beneficial to implement a feature to automatically fetch the latest key. Especially automated systems that do not receive frequent maintenance/dependency updates might benefit from such a feature. This feature could of course be optional, in case there is a chance of breaking old code.

Thank you for your consideration!

**Comment by extremeheat** [comment]
This key is normally embedded inside a vanilla client/server, not fetched from a server, so it changing will indeed be a breaking change. Since the change you mention is the first change since the introduction of authentication (for unknown reasons), it may not be necessary to automate the updating of it yet. But if this does get changed again in next few months, I agree we can add some workflow here to update the key.

The reason this key is embedded is because Minecraft bedrock authentication is designed to work even when offline. So maintaining a hardcoded copy of the Mojang public key allows for offline verification.

**Comment by outsparkled** [comment]
Ah, that makes sense.
Thanks for the explanation. Understanding now that this is not a frequent occurrence, I agree that fetching the key automatically is not really needed.

Should such key changes occur more frequently in the future, I would be happy to help implement such a feature.

Closing since it does not seem necessary at this time.
